apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
{{ include "imagePullSecret" . | indent 6 }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      containers:
      - name: chargepoint-api
        image: {{ include "image_repository" . }}/user-svc:{{ include "image_tag" . }}
        resources:
          requests:
            cpu: 100m
            memory: 128M
        env:
        - name: MONGODB_HOST
          value: {{ .Values.db.host }}
        - name: MONGODB_USERNAME
          value: user
        - name: MONGODB_PORT
          value: {{ .Values.db.port | quote}}
        - name: MONGODB_PASSWORD
          value: {{ .Values.db.password }}
        - name: LOG_LEVEL
          value: {{ .Values.log_level }}
        ports:
            - containerPort: 8080
      restartPolicy: Always
