apiVersion: v1
kind: Service
metadata:
  labels:
    app: chargepoint
  name: chargepoint
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: chargepoint
  type: ClusterIP